name: Backend

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: write

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@1.x
    with:
      enable_backend_testing: false
      enable_phpstan: true
      backend_directory: .
      php_versions: '["8.1", "8.2", "8.3", "8.4", "8.5"]'
