name: Frontend

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: write

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_frontend.yml@1.x
    with:
      enable_bundlewatch: false
      enable_prettier: true
      enable_typescript: true
      frontend_directory: ./js
      backend_directory: .
      js_package_manager: yarn
      main_git_branch: main
